{
	"version": 1701730997,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/blocochaocomneon.png",
		"images/fundo-sheet0.png",
		"images/pacm-sheet0.png",
		"images/tiledbackground.png",
		"images/spritepac-sheet0.png",
		"images/spritepac-sheet1.png",
		"images/botaomenu-sheet0.png",
		"images/pontos-sheet0.png",
		"images/inimigo_vermelho-sheet0.png",
		"images/parede_invisivel-sheet0.png",
		"images/direita-sheet0.png",
		"images/esquerda-sheet0.png",
		"images/bolinhabranca-sheet0.png",
		"images/inimigo_amarelo-sheet0.png",
		"images/inimigo_amarelo-sheet1.png",
		"images/inimigo_amarelo-sheet2.png",
		"images/inimigo_roza-sheet0.png",
		"images/inimigo_roza-sheet1.png",
		"images/inimigo_roza-sheet2.png",
		"images/textomenu-sheet0.png",
		"images/gameoverbutom-sheet0.png",
		"images/letreirogameover-sheet0.png",
		"images/win-sheet0.png",
		"images/cereja-sheet0.png",
		"images/misteriosinho-sheet0.png",
		"images/fadeout-sheet0.png",
		"images/fadeout-sheet1.png",
		"images/fadeout-sheet2.png",
		"images/botao_musica-sheet0.png",
		"images/botao_musica2-sheet0.png",
		"images/botao_musica3-sheet0.png",
		"images/botao_musica4-sheet0.png",
		"images/paradegracinha-sheet0.png",
		"images/spritepacrosa-sheet0.png",
		"images/spritepacrosa-sheet1.png",
		"images/spritepacverde-sheet0.png",
		"images/spritepacverde-sheet1.png",
		"images/spritepacazul-sheet0.png",
		"images/spritepacazul-sheet1.png",
		"media/som de pulo.ogg",
		"media/cartoon - c u again feat. mikk mäe (cartoon vs futuristik vip) [ncs release].ogg",
		"media/lil nas x - old town road (feat. billy ray cyrus)(mp3_160k).ogg",
		"media/mario-vs-pacman-remix(mp3_128k).ogg",
		"media/super mario world trap remix(mp3_160k).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}